'use client';
import {useEffect,useMemo,useState} from 'react';
import {get,send} from '../../lib/api';
import {formatError} from '../../lib/errors';
import {useCustomer} from '../../components/CustomerContext';
const remoteProviders=['openai','azure_openai','anthropic','gemini','openrouter','bedrock'];
const help:Record<string,string>={openrouter:'https://openrouter.ai/api/v1',ollama:'http://localhost:11434',lm_studio:'http://localhost:1234/v1',enterprise:'https://llm.company.local/v1'};
export default function Settings(){
 const {customer}=useCustomer();const [tab,setTab]=useState<'global'|'customer'>('customer'),[global,setGlobal]=useState<any>(),[local,setLocal]=useState<any>(),[diagnostics,setDiagnostics]=useState<any>(),[dirty,setDirty]=useState(false),[notice,setNotice]=useState(''),[warning,setWarning]=useState(''),[aiTest,setAiTest]=useState<any>(),[embeddingTest,setEmbeddingTest]=useState<any>(),[testing,setTesting]=useState<'ai'|'embedding'|''>(''),[updatingAIKey,setUpdatingAIKey]=useState(false),[updatingEmbeddingKey,setUpdatingEmbeddingKey]=useState(false),[reindexing,setReindexing]=useState(false),[modelLists,setModelLists]=useState<any>({chat:[],embedding:[]}),[fetchingModels,setFetchingModels]=useState<'chat'|'embedding'|''>(''),[modelError,setModelError]=useState('');
 const load=()=>Promise.all([get('/api/settings/global'),customer?get(`/api/customers/${customer.id}/settings`):null,customer?get(`/api/customers/${customer.id}/settings/diagnostics`):null]).then(([g,c,d])=>{setGlobal(g);setLocal(c);setDiagnostics(d);setDirty(false)}).catch(e=>setWarning(formatError(e)));useEffect(()=>{void load()},[customer]);
 const active=tab==='global'?global:local,inherited=tab==='customer'&&!local?.is_override,errors=useMemo(()=>active?validate(active):{},[active]);
 if(!global||!local)return <div className="loading"><span className="spinner"/>Loading settings…</div>;
 function update(name:string,value:any){(tab==='global'?setGlobal:setLocal)((current:any)=>({...current,[name]:value}));setDirty(true);setNotice('')}
 const payload=()=>({...active,ai_api_key:active.ai_api_key||'',embedding_api_key:active.embedding_api_key||''});
 async function save(){if(Object.keys(errors).length)return;const previous={provider:active.embedding_provider,model:active.embedding_model,size:active.chunk_size,overlap:active.chunk_overlap};const path=tab==='global'?'/api/settings/global':`/api/customers/${customer?.id}/settings`;const result=await send(path,'PUT',payload());setNotice('✓ Saved Successfully');setDirty(false);setUpdatingAIKey(false);setUpdatingEmbeddingKey(false);if(previous.provider!==result.embedding_provider||previous.model!==result.embedding_model||previous.size!==result.chunk_size||previous.overlap!==result.chunk_overlap)setWarning('Embedding settings changed. Existing documents should be re-indexed to use the new embedding model.');await load()}
 async function enableOverride(){await send(`/api/customers/${customer?.id}/settings/override`,'POST');setNotice('Customer-specific override active. Add customer API keys if required.');await load()}
 async function reset(){await send(`/api/customers/${customer?.id}/settings/reset`,'POST');setNotice('Reset to Global Default');setWarning('Effective embedding settings may have changed. Re-index is recommended.');await load()}
 async function test(kind:'ai'|'embedding'){const relevant=kind==='ai'?['ai_base_url','llm_model','ai_api_key']:['embedding_base_url','embedding_model','embedding_api_key'];if(relevant.some(x=>errors[x]))return;setTesting(kind);kind==='ai'?setAiTest(undefined):setEmbeddingTest(undefined);const prefix=tab==='global'?'/api/settings/global':`/api/customers/${customer?.id}/settings`;try{const result=await send(`${prefix}/test-${kind}`,'POST',payload());kind==='ai'?setAiTest(result):setEmbeddingTest(result)}catch(e:any){let detail:any={message:e.message};try{detail=JSON.parse(e.message).detail||detail}catch{};kind==='ai'?setAiTest({ok:false,...detail}):setEmbeddingTest({ok:false,...detail})}finally{setTesting('');if(customer)setDiagnostics(await get(`/api/customers/${customer.id}/settings/diagnostics`))}}
 async function reindex(){if(!customer)return;setReindexing(true);try{await send(`/api/customers/${customer.id}/documents/reindex-all`,'POST');setWarning('');setNotice('Re-index completed successfully.');setDiagnostics(await get(`/api/customers/${customer.id}/settings/diagnostics`))}catch(e:any){setWarning(e.message)}finally{setReindexing(false)}}
 async function fetchModels(kind:'chat'|'embedding'){setFetchingModels(kind);setModelError('');const prefix=tab==='global'?'/api/settings/global':`/api/customers/${customer?.id}/settings`;try{const result=await send(`${prefix}/models/${kind}`,'POST',payload());setModelLists((current:any)=>({...current,[kind]:result.models||[]}))}catch(e:any){setModelError(e.message)}finally{setFetchingModels('')}}
 const needsAttention=Object.keys(errors).length>0||diagnostics?.documents_requiring_reindex>0||diagnostics?.failed_index>0;
 return <><div className="pagehead"><div><div className="eyebrow">Enterprise configuration</div><h1>Settings</h1><p className="sub">Understand exactly which configuration is active, where it comes from, and whether it is healthy.</p></div><div className="status-stack">{dirty?<span className="badge warning-badge">Unsaved Changes</span>:notice&&<span className="badge success">✓ Saved Successfully</span>}</div></div>
 <EffectiveCard config={local} diagnostics={diagnostics} needsAttention={needsAttention}/>
 <div className="settings-tabs" role="tablist"><button role="tab" aria-selected={tab==='global'} className={tab==='global'?'active':''} onClick={()=>{setTab('global');setDirty(false);setNotice('');setWarning('')}}>🌍 Global Default Settings</button><button role="tab" aria-selected={tab==='customer'} className={tab==='customer'?'active':''} onClick={()=>{setTab('customer');setDirty(false);setNotice('');setWarning('')}}>🏢 Customer Settings – {customer?.name}</button></div>
 {tab==='global'?<div className="scope-intro"><strong>🌍 Global Default Settings</strong><span>These settings are inherited by all customers unless overridden.</span></div>:<div className={`inheritance-banner ${local.is_override?'override':'inherited'}`}><div><strong>{local.is_override?'🟡 Customer Override Active':'✓ Using Global Default Settings'}</strong><span>{local.is_override?`These values apply only to ${customer?.name}.`:'Inherited values are read-only and update automatically with global defaults.'}</span></div>{local.is_override?<button className="secondary" onClick={reset}>Reset to Global Default</button>:<button onClick={enableOverride}>Override Settings</button>}</div>}
 {warning&&<div className="notice warning-notice">⚠ {warning} <button disabled={reindexing} onClick={reindex}>{reindexing?'Re-indexing…':'Re-index All Documents'}</button></div>}
 {!warning&&diagnostics?.documents_requiring_reindex>0&&<div className="notice warning-notice">⚠ Existing documents were indexed using a different embedding configuration. Re-index is recommended. <button disabled={reindexing} onClick={reindex}>{reindexing?'Re-indexing…':'Re-index All Documents'}</button></div>}
 <SettingsForm data={active} disabled={inherited} errors={errors} update={update} aiTest={aiTest} embeddingTest={embeddingTest} testing={testing} test={test} updatingAIKey={updatingAIKey} setUpdatingAIKey={setUpdatingAIKey} updatingEmbeddingKey={updatingEmbeddingKey} setUpdatingEmbeddingKey={setUpdatingEmbeddingKey} modelLists={modelLists} fetchingModels={fetchingModels} fetchModels={fetchModels} modelError={modelError}/>
 {!inherited&&<div className="sticky-save"><span>{dirty?'Unsaved Changes':notice||'No unsaved changes'}</span><button disabled={!dirty||Object.keys(errors).length>0} onClick={save}>{tab==='global'?'Save Global Defaults':'Save Customer Settings'}</button></div>}
 <Diagnostics data={diagnostics}/></>;
}
function validate(x:any){const e:Record<string,string>={};const url=(name:string)=>{if(x[name])try{new URL(x[name])}catch{e[name]='Enter a valid URL including http:// or https://'}};url('ai_base_url');url('embedding_base_url');if(!x.llm_model?.trim())e.llm_model='Chat model is required';if(!x.embedding_model?.trim())e.embedding_model='Embedding model is required';if(remoteProviders.includes(x.llm_provider)&&!x.ai_api_key_configured&&!x.ai_api_key)e.ai_api_key='API key is required';if(remoteProviders.includes(x.embedding_provider)&&!x.embedding_api_key_configured&&!x.embedding_api_key)e.embedding_api_key='API key is required';if(x.custom_headers)try{const value=JSON.parse(x.custom_headers);if(!value||Array.isArray(value)||typeof value!=='object'||Object.values(value).some(v=>typeof v!=='string'))throw new Error()}catch{e.custom_headers='Use a JSON object with string values'}if(x.temperature<0||x.temperature>2)e.temperature='Temperature must be between 0 and 2';if(x.top_k<1)e.top_k='Top K must be at least 1';if(x.chunk_size<100)e.chunk_size='Chunk size must be at least 100';if(x.chunk_overlap<0||x.chunk_overlap>=x.chunk_size)e.chunk_overlap='Overlap must be smaller than chunk size';return e}
function SettingsForm(p:any){const field=(name:string,label:string,type='text',tip='')=><label title={tip}>{label}<input disabled={p.disabled} type={type} value={p.data[name]??''} aria-invalid={!!p.errors[name]} onChange={e=>p.update(name,type==='number'?Number(e.target.value):e.target.value)}/>{p.errors[name]&&<small className="field-error">{p.errors[name]}</small>}</label>;const custom=['openai_compatible','enterprise'].includes(p.data.llm_provider)||p.data.embedding_provider==='custom';return <>
 {custom&&<Section n="00" title="Local / Custom Enterprise Provider" text="Manual configuration works without model discovery."><div className="card formgrid">{field('provider_display_name','Provider Display Name')}{field('chat_endpoint_path','Chat Endpoint Path')}{field('embedding_endpoint_path','Embedding Endpoint Path')}<label>OpenAI-compatible mode<select disabled={p.disabled} value={String(p.data.openai_compatible_mode)} onChange={e=>p.update('openai_compatible_mode',e.target.value==='true')}><option value="true">On</option><option value="false">Off</option></select></label><label>Custom Headers (JSON)<textarea disabled={p.disabled} value={p.data.custom_headers||''} aria-invalid={!!p.errors.custom_headers} placeholder={p.data.custom_headers_configured?'Configured — enter JSON to replace':'{\n  "X-Organization": "MedNova"\n}'} onChange={e=>p.update('custom_headers',e.target.value)}/><small className="provider-help">Stored write-only. Use string values; authorization headers are supported.</small>{p.errors.custom_headers&&<small className="field-error">{p.errors.custom_headers}</small>}</label></div></Section>}
 <Section n="01" title="AI Provider" text="Generates grounded questionnaire answers."><div className="card formgrid"><label>AI Provider<select disabled={p.disabled} value={p.data.llm_provider} onChange={e=>p.update('llm_provider',e.target.value)}>{p.data.available_llms.map((x:string)=><option key={x}>{x}</option>)}</select><ProviderHelp provider={p.data.llm_provider}/></label>{field('ai_base_url','AI Base URL')}{p.data.llm_provider==='openrouter'?<ModelPicker kind="chat" label="Chat Model" value={p.data.llm_model} models={p.modelLists.chat} recommended={p.data.recommended_chat_model} disabled={p.disabled} loading={p.fetchingModels==='chat'} fetch={()=>p.fetchModels('chat')} update={(v:string)=>p.update('llm_model',v)}/>:field('llm_model','Chat Model')}<KeyField kind="AI" configured={p.data.ai_api_key_configured} updating={p.updatingAIKey} setUpdating={p.setUpdatingAIKey} disabled={p.disabled} value={p.data.ai_api_key||''} update={(v:string)=>p.update('ai_api_key',v)} error={p.errors.ai_api_key}/>{field('temperature','Temperature','number','Recommended range: 0–1 for grounded answers.')}{field('max_tokens','Max Tokens','number')}<div><button className="secondary" disabled={p.testing==='ai'||p.disabled} onClick={()=>p.test('ai')}>{p.testing==='ai'?'Testing AI…':'Test AI Connection'}</button></div>{p.aiTest&&<ConnectionResult kind="ai" data={p.aiTest}/>}</div></Section>
 <Section n="02" title="Embedding Provider" text="Indexes documents for semantic retrieval."><div className="card formgrid"><label>Embedding Provider<select disabled={p.disabled} value={p.data.embedding_provider} onChange={e=>p.update('embedding_provider',e.target.value)}>{p.data.available_embeddings.map((x:string)=><option key={x}>{x}</option>)}</select><ProviderHelp provider={p.data.embedding_provider}/></label>{field('embedding_base_url','Embedding Base URL')}{p.data.embedding_provider==='openrouter'?<ModelPicker kind="embedding" label="Embedding Model" value={p.data.embedding_model} models={p.modelLists.embedding} recommended={p.data.recommended_embedding_model} disabled={p.disabled} loading={p.fetchingModels==='embedding'} fetch={()=>p.fetchModels('embedding')} update={(v:string)=>p.update('embedding_model',v)}/>:field('embedding_model','Embedding Model')}<KeyField kind="Embedding" configured={p.data.embedding_api_key_configured} updating={p.updatingEmbeddingKey} setUpdating={p.setUpdatingEmbeddingKey} disabled={p.disabled} value={p.data.embedding_api_key||''} update={(v:string)=>p.update('embedding_api_key',v)} error={p.errors.embedding_api_key}/><div><button className="secondary" disabled={p.testing==='embedding'||p.disabled} onClick={()=>p.test('embedding')}>{p.testing==='embedding'?'Testing Embedding…':'Test Embedding Connection'}</button></div>{p.embeddingTest&&<ConnectionResult kind="embedding" data={p.embeddingTest}/>} {p.modelError&&<small className="field-error">{p.modelError}</small>}</div></Section>
 <Section n="03" title="Retrieval Settings" text="Controls evidence selection and document chunking."><div className="card formgrid">{field('top_k','Top K','number')}{field('top_p','Top P','number')}{field('chunk_size','Chunk Size','number')}{field('chunk_overlap','Chunk Overlap','number')}{field('timeout','Timeout','number')}{field('retry_count','Retry Count','number')}</div></Section><Section n="04" title="Prompt Template" text="Grounding instructions for every generated answer."><div className="card"><textarea disabled={p.disabled} value={p.data.prompt_instructions} onChange={e=>p.update('prompt_instructions',e.target.value)}/></div></Section></>}
function KeyField(p:any){return <label>{p.kind} API Key<div className="key-status"><span className={`badge ${p.configured?'success':'ready'}`}>{p.configured?'Configured':'Not Configured'}</span>{!p.disabled&&!p.updating&&<button className="mini secondary" onClick={()=>p.setUpdating(true)}>Update API Key</button>}</div>{p.updating&&<input type="password" autoComplete="new-password" value={p.value} placeholder="Enter replacement key" onChange={e=>p.update(e.target.value)}/>} {p.error&&<small className="field-error">{p.error}</small>}</label>}
function ModelPicker(p:any){const selected=p.models.find((x:any)=>x.id===p.value);return <label>{p.label}<select disabled={p.disabled} value={p.value} onChange={e=>p.update(e.target.value)}><option value={p.value}>{selected?.name||p.value}</option>{p.models.filter((x:any)=>x.id!==p.value).map((x:any)=><option key={x.id} value={x.id}>{x.name} · {x.free?'Free':'Paid'} · {x.id}</option>)}</select><div className="key-status"><button type="button" className="mini secondary" disabled={p.disabled||p.loading} onClick={p.fetch}>{p.loading?'Fetching…':`Fetch ${p.label}s`}</button><button type="button" className="mini secondary" disabled={p.disabled} onClick={()=>p.update(p.recommended)}>Use recommended</button></div>{selected&&<small className="provider-help">ID: {selected.id} · Provider: {selected.provider} · {selected.free?'Free':'Paid'} · Context: {selected.context_length?.toLocaleString()||'Not published'} · Chat: {selected.supports_chat?'Yes':'No'} · Embeddings: {selected.supports_embeddings?'Yes':'No'}{p.kind==='embedding'?` · Dimension: ${selected.embedding_dimension||'determined on test/index'}`:''}</small>}{p.kind==='embedding'&&<small className="field-error">Changing this model requires re-indexing. Chat model changes do not.</small>}</label>}
function ProviderHelp({provider}:{provider:string}){const value=help[provider];return value?<small className="provider-help">Suggested base URL: <code>{value}</code></small>:null}
function ConnectionResult({kind,data}:{kind:string;data:any}){return <div className={`connection-result ${data.ok?'ok':'bad'}`}><strong>{data.ok?'✓ Connected':'✕ Failed'}</strong><span>Provider: {formatError(data.provider||'—')}</span>{kind==='ai'?<><span>Base URL: {formatError(data.base_url||'—')}</span><span>Chat Model: {formatError(data.model||'—')}</span><span>Latency: {String(data.latency_ms??'—')} ms</span>{data.ok&&<span>Response: {formatError(data.response)}</span>}</>:<><span>Embedding Model: {formatError(data.model||'—')}</span>{data.ok&&<span>Vector Dimension: {String(data.vector_dimension??'—')}</span>}<span>Latency: {String(data.latency_ms??'—')} ms</span></>}{!data.ok&&<span className="test-error">{formatError(data.message)}</span>}</div>}
function EffectiveCard({config,diagnostics,needsAttention}:{config:any;diagnostics:any;needsAttention:boolean}){return <div className="card effective-card"><div><div className="panel-label">CURRENT EFFECTIVE CONFIGURATION</div><h2>{config.settings_source==='customer_override'?'Customer Override':'Global Default'}</h2></div><Metric label="AI Provider" value={config.llm_provider}/><Metric label="Chat Model" value={config.llm_model}/><Metric label="Embedding Provider" value={config.embedding_provider}/><Metric label="Embedding Model" value={config.embedding_model}/><div><span className={`badge ${needsAttention?'warning-badge':'success'}`}>{needsAttention?'Needs Attention':'Ready'}</span>{diagnostics?.documents_requiring_reindex>0&&<small>{diagnostics.documents_requiring_reindex} documents need re-index</small>}</div></div>}
function Diagnostics({data}:{data:any}){if(!data)return null;const indexed=(data.indexed_models||[]).map((x:any)=>`${x.provider} / ${x.model} (${x.dimension}D, ${x.documents} docs)`).join('; ')||'None';return <section className="diagnostics-summary"><div className="sectionhead"><div><h2>Diagnostics Summary</h2><p className="label">Current indexing and connection health for this customer.</p></div></div><div className="card diagnostic-summary-grid"><Metric label="Documents" value={data.documents}/><Metric label="Indexed Documents" value={data.indexed_documents}/><Metric label="Pending Index" value={data.pending_index}/><Metric label="Failed Index" value={data.failed_index}/><Metric label="Current Chat Model" value={data.chat_model}/><Metric label="Current Embedding Model" value={data.embedding_model}/><Metric label="Model Used During Indexing" value={indexed}/><Metric label="Re-index Required" value={data.reindex_required?'Yes':'No'}/><Metric label="Last Re-index" value={data.last_reindex?new Date(data.last_reindex).toLocaleString():'Never'}/><Metric label="Last AI Test" value={testLabel(data.last_ai_test)}/><Metric label="Last Embedding Test" value={testLabel(data.last_embedding_test)}/></div></section>}
const testLabel=(x:any)=>!x?'Never':`${x.ok?'Connected':'Failed'} · ${new Date(x.at).toLocaleString()}`;function Metric({label,value}:{label:string;value:any}){return <div className="summary-metric"><span>{label}</span><strong>{value??'—'}</strong></div>}function Section({n,title,text,children}:{n:string;title:string;text:string;children:React.ReactNode}){return <section className="settings-section"><div className="settings-title"><span>{n}</span><div><h2>{title}</h2><p className="label">{text}</p></div></div>{children}</section>}
