'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {get} from '../lib/api';
import {useCustomer} from '../components/CustomerContext';
const steps=[['1','Create Customer','Set up an isolated organization workspace.','/customers'],['2','Upload Knowledge Documents','Add approved company evidence.','/knowledge'],['3','Upload Questionnaire','Extract customer questions.','/questionnaires'],['4','Generate Answers','Draft answers from retrieved evidence.','/questionnaires'],['5','Review and Export','Approve, edit, and deliver the result.','/questionnaires']];
export default function Dashboard(){const {customer,customers}=useCustomer();const [d,setD]=useState<any>();useEffect(()=>{if(customer)get(`/api/customers/${customer.id}/dashboard`).then(setD)},[customer]);if(!customer)return <Onboarding/>;return <><div className="pagehead"><div><div className="eyebrow">{customer.name}</div><h1>Questionnaire workspace</h1><p className="sub">A clear path from approved knowledge to customer-ready answers.</p></div><Link className="button" href="/questionnaires">New questionnaire</Link></div><div className="grid"><Stat value={d?.documents} label="Knowledge documents"/><Stat value={d?.questionnaires} label="Questionnaires"/><Stat value={d?.llm_provider} label={`AI · ${d?.embedding_provider||'—'} embeddings`}/><Stat value={customers.filter(x=>!x.archived).length} label="Active customers"/></div><div className="sectionhead"><div><h2>Reviewer productivity</h2><p className="label">Trusted-answer reuse and review throughput.</p></div></div><div className="grid productivity"><Stat value={d?.questions_generated||0} label="Questions generated"/><Stat value={d?.questions_approved||0} label="Questions approved"/><Stat value={d?.golden_answers||0} label="Golden answers"/><Stat value={d?.answers_reused||0} label="Answers reused"/><Stat value={d?.manual_reviews||0} label="Manual reviews"/><Stat value={`${Math.round((d?.average_confidence||0)*100)}%`} label="Average confidence"/><Stat value={`${d?.average_review_seconds||0}s`} label="Average review time"/><Stat value={`${d?.estimated_minutes_saved||0}m`} label="Estimated time saved"/></div><div className="sectionhead"><div><h2>Getting started</h2><p className="label">Follow the workflow from evidence to export.</p></div></div><div className="workflow">{steps.map((x,i)=><Link href={x[3]} className={`workflow-step ${(i===0||d?.documents>0&&i===1||d?.questionnaires>0&&i>=2)?'done':''}`} key={x[0]}><span>{x[0]}</span><div><strong>{x[1]}</strong><div className="label">{x[2]}</div></div></Link>)}</div><div className="card"><h2>Recent activity</h2>{d?.recent_activity?.length?d.recent_activity.map((x:any)=><div className="row" key={x.id}><span className="activity-icon">✓</span><span className="grow">{x.action.replaceAll('_',' ')}</span><span className="label">{new Date(x.created_at).toLocaleString()}</span></div>):<Empty title="No activity yet" text="Upload a document to begin building this customer’s answer workspace." href="/knowledge" cta="Upload knowledge"/>}</div></>}
function Stat({value,label}:{value:any;label:string}){return <div className="card"><div className="stat">{value??'—'}</div><div className="label">{label}</div></div>}
function Empty({title,text,href,cta}:{title:string;text:string;href:string;cta:string}){return <div className="empty"><div className="empty-icon">◇</div><h2>{title}</h2><p>{text}</p><Link className="button" href={href}>{cta}</Link></div>}
function Onboarding(){return <div className="onboarding"><div className="eyebrow">Welcome</div><h1>Answer customer questionnaires with confidence</h1><p className="sub">Set up your first organization, add approved knowledge, and create traceable answers in five clear steps.</p><div className="workflow large">{steps.map(x=><div className="workflow-step" key={x[0]}><span>{x[0]}</span><div><strong>{x[1]}</strong><div className="label">{x[2]}</div></div></div>)}</div><Link className="button" href="/customers">Create your first customer →</Link></div>}
